(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const number=id=>Number($(id)?.value||0);
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number.isFinite(n)?n:0);
  const money2=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number.isFinite(n)?n:0);
  const percent=n=>(n*100).toFixed(2)+'%';
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function rows(items){return '<div class="result-list">'+items.map(x=>'<div class="result-row"><span>'+esc(x[0])+'</span><span>'+esc(x[1])+'</span></div>').join('')+'</div>'}
  function show(label,primary,items,note){const box=$('results');box.innerHTML='<div class="result-kicker">'+esc(label)+'</div><div class="result-primary">'+esc(primary)+'</div>'+rows(items)+(note?'<p class="result-note">'+note+'</p>':'');box.focus();}
  function error(message){$('results').innerHTML='<div class="calc-error" role="alert">'+esc(message)+'</div>';}
  function payment(principal,annualRate,years){const n=years*12,r=annualRate/1200;if(principal<=0||n<=0)return 0;if(!r)return principal/n;return principal*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)}
  const taxBrackets={
    single:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[640600,.35],[Infinity,.37]],
    married:[[24800,.10],[100800,.12],[211400,.22],[403550,.24],[512450,.32],[768700,.35],[Infinity,.37]],
    head:[[17700,.10],[67450,.12],[105700,.22],[201750,.24],[256200,.32],[640600,.35],[Infinity,.37]],
    mfs:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[384350,.35],[Infinity,.37]]
  };
  const deductions={single:16100,married:32200,head:24150,mfs:16100};
  function incomeTax(taxable,status){let tax=0,previous=0;for(const [limit,rate] of taxBrackets[status]){if(taxable<=previous)break;const slice=Math.min(taxable,limit)-previous;tax+=slice*rate;previous=limit;}return Math.max(0,tax)}
  function mortgage(){const price=number('price'),down=number('down'),rate=number('rate'),years=number('term'),tax=number('propertyTax'),insurance=number('insurance'),pmiRate=number('pmiRate'),closingRate=number('closingRate');if(price<=0||down<0||down>=price||rate<0||years<=0)return error('Enter a valid price, down payment, interest rate, and loan term.');const principal=price-down,ltv=principal/price,pi=payment(principal,rate,years),pmi=ltv>.80?principal*(pmiRate/100)/12:0,monthlyTax=tax/12,monthlyInsurance=insurance/12,total=pi+pmi+monthlyTax+monthlyInsurance,closing=price*closingRate/100,cash=down+closing;show('Estimated total monthly payment',money2(total),[['Principal and interest',money2(pi)],['Property tax',money2(monthlyTax)],['Homeowners insurance',money2(monthlyInsurance)],['Estimated PMI',money2(pmi)],['Loan-to-value',percent(ltv)],['Estimated cash to close',money(cash)]],pmi?'PMI is estimated from the rate you supplied. For many conventional loans, you may request cancellation at 80% of original value; automatic termination is generally scheduled at 78% if current.':'No PMI estimate is included because the entered down payment is at least 20%.');}
  function freelancer(){const revenue=number('revenue'),expenses=number('expenses'),wages=number('wages'),withholding=number('withholding'),credits=number('credits'),priorTax=number('priorTax'),priorAgi=number('priorAgi'),status=$('filingStatus').value;if(revenue<0||expenses<0||expenses>revenue)return error('Enter non-negative revenue and expenses no greater than revenue.');const profit=revenue-expenses,seBase=profit*.9235,ss=Math.min(seBase,Math.max(0,184500-wages))*.124,medicare=seBase*.029,threshold=status==='married'?250000:status==='mfs'?125000:200000,additional=Math.max(0,wages+seBase-threshold)*.009,seTax=ss+medicare+additional,deduction=seTax/2,taxable=Math.max(0,profit+wages-deduction-deductions[status]),income=Math.max(0,incomeTax(taxable,status)-credits),total=income+seTax,currentTarget=total*.9,priorMultiplier=priorAgi>150000||(status==='mfs'&&priorAgi>75000)?1.1:1,priorTarget=priorTax>0?priorTax*priorMultiplier:Infinity,safe=Math.min(currentTarget,priorTarget),remaining=Math.max(0,safe-withholding),quarter=remaining/4;show('Suggested quarterly federal set-aside',money2(quarter),[['Net business profit',money(profit)],['Self-employment tax',money(seTax)],['Estimated income tax',money(income)],['Annual safe-harbor target',money(safe===Infinity?currentTarget:safe)],['Less expected withholding',money(withholding)],['Estimated annual payments needed',money(remaining)]],'Estimate uses the 2026 IRS 92.35% Schedule SE factor, $184,500 Social Security wage base, 2026 ordinary brackets, and the smaller of the current-year 90% or entered prior-year safe-harbor target. It excludes state tax, QBI, itemized deductions, most credits, and special income.');}
  function simulateDebts(raw,extra,mode){let debts=raw.map((d,i)=>({...d,i})),month=0,interest=0,max=1200;const monthlyBudget=raw.reduce((sum,d)=>sum+d.min,0)+extra;while(debts.some(d=>d.balance>.005)&&month<max){month++;for(const d of debts){if(d.balance<=0)continue;const charge=d.balance*d.apr/1200;d.balance+=charge;interest+=charge;}let budget=monthlyBudget;for(const d of debts){if(d.balance<=0)continue;const paid=Math.min(d.balance,d.min,budget);d.balance-=paid;budget-=paid;}let active=debts.filter(d=>d.balance>.005).sort(mode==='snowball'?(a,b)=>a.balance-b.balance||b.apr-a.apr:(a,b)=>b.apr-a.apr||a.balance-b.balance);while(budget>.005&&active.length){const target=active[0],paid=Math.min(target.balance,budget);target.balance-=paid;budget-=paid;if(target.balance<=.005)active.shift();}}return month>=max?null:{months:month,interest};}
  function debt(){const raw=[1,2,3].map(i=>({name:$('debtName'+i).value||'Debt '+i,balance:number('debtBalance'+i),apr:number('debtApr'+i),min:number('debtMin'+i)})).filter(d=>d.balance>0);const extra=number('extra');if(!raw.length||raw.some(d=>d.apr<0||d.min<=0)||extra<0)return error('Add at least one debt with a positive balance and minimum payment.');const snow=simulateDebts(raw,extra,'snowball'),avalanche=simulateDebts(raw,extra,'avalanche');if(!snow||!avalanche)return error('The entered payments do not pay down the balances. Increase minimum or extra payments.');const winner=avalanche.interest<=snow.interest?'Debt avalanche':'Debt snowball';show('Lower-interest strategy',winner,[['Snowball payoff time',snow.months+' months'],['Snowball interest',money(snow.interest)],['Avalanche payoff time',avalanche.months+' months'],['Avalanche interest',money(avalanche.interest)],['Interest saved with avalanche',money(Math.max(0,snow.interest-avalanche.interest))]],'The model compounds interest monthly, pays every listed minimum, then sends the extra amount to the smallest balance (snowball) or highest APR (avalanche). Actual card timing, fees, and daily compounding can differ.');}
  function w4(){const income1=number('income1'),income2=number('income2'),other=number('otherIncome'),deduct=number('deductions'),credits=number('credits'),withheld=number('annualWithholding'),periods=number('payPeriods');if(income1<0||income2<0||periods<=0)return error('Enter valid annual wages and remaining pay periods.');const gross=income1+income2+other,taxable=Math.max(0,gross-Math.max(32200,deduct)),tax=Math.max(0,incomeTax(taxable,'married')-credits),gap=tax-withheld,per=Math.max(0,gap/periods);show('Estimated additional withholding per remaining paycheck',money2(per),[['Combined projected income',money(gross)],['Estimated taxable income',money(taxable)],['Estimated 2026 federal income tax',money(tax)],['Expected withholding before adjustment',money(withheld)],['Projected shortfall / (surplus)',money(gap)]],gap<=0?'Your entered withholding meets or exceeds this simplified projected federal income-tax amount.':'Enter the additional amount on only one Form W-4, generally for the higher-paying job. For an official result, confirm with the IRS Tax Withholding Estimator.');}
  function va(){const price=number('price'),down=number('down'),rate=number('rate'),years=number('term'),exempt=$('exempt').value==='yes',use=$('use').value,finance=$('financeFee').value==='yes';if(price<=0||down<0||down>=price||years<=0||rate<0)return error('Enter a valid price, down payment, rate, and term.');const loan=price-down,downPct=down/price;let feeRate=0;if(!exempt){if(downPct>=.10)feeRate=.0125;else if(downPct>=.05)feeRate=.015;else feeRate=use==='first'?.0215:.033;}const fee=loan*feeRate,financed=loan+(finance?fee:0),monthly=payment(financed,rate,years),cash=down+(finance?0:fee);show('Estimated VA funding fee',money2(fee),[['Official fee rate',percent(feeRate)],['Base loan amount',money(loan)],['Financed loan amount',money(financed)],['Principal and interest',money2(monthly)+'/month'],['Down payment plus fee due',money(cash)]],exempt?'You selected an exemption, so the funding fee is $0. Confirm eligibility on your Certificate of Eligibility and with VA or your lender.':'VA purchase-loan rates shown are effective April 7, 2023 and remain listed by VA in 2026. VA loans do not require monthly PMI. Other closing costs are not included.');}
  const calculators={mortgage,freelancer,debt,w4,va};
  function params(){const p=new URLSearchParams(location.search);document.querySelectorAll('[data-param]').forEach(el=>{if(p.has(el.dataset.param))el.value=p.get(el.dataset.param);});if([...p].length)$('calculate')?.click();}
  function share(){const u=new URL(location.origin+location.pathname);document.querySelectorAll('[data-param]').forEach(el=>{if(el.value!=='')u.searchParams.set(el.dataset.param,el.value);});navigator.clipboard.writeText(u.toString()).then(()=>{const m=$('shareStatus');m.textContent='Shareable link copied.';setTimeout(()=>m.textContent='',3000);});}
  function reset(){document.querySelector('form')?.reset();$('results').innerHTML='<p class="ymyl-empty">Enter your details to see a transparent estimate and the assumptions behind it.</p>';history.replaceState({},'',location.pathname);}
  document.addEventListener('DOMContentLoaded',()=>{const type=document.body.dataset.calculator;if(!calculators[type])return;$('calculatorForm').addEventListener('submit',e=>{e.preventDefault();calculators[type]();});$('reset')?.addEventListener('click',reset);$('share')?.addEventListener('click',share);params();});
})();
