(function(){
  'use strict';
  const $=id=>document.getElementById(id),num=id=>Number($(id)?.value||0);
  const fmt=(n,d=1)=>Number(n).toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rows=a=>'<div class="result-list">'+a.map(x=>'<div class="result-row"><span>'+esc(x[0])+'</span><span>'+esc(x[1])+'</span></div>').join('')+'</div>';
  function show(label,primary,items,note){const el=$('results');el.innerHTML='<div class="result-kicker">'+esc(label)+'</div><div class="result-primary">'+esc(primary)+'</div>'+rows(items)+'<p class="result-note">'+note+'</p>';el.focus();}
  function fail(message){$('results').innerHTML='<div class="calc-error" role="alert">'+esc(message)+'</div>';}
  function pregnancy(){const height=num('height'),before=num('beforeWeight'),current=num('currentWeight'),week=num('week'),babies=$('babies').value;if(height<48||height>84||before<=0||current<=0||week<1||week>42)return fail('Enter plausible height, weight, and pregnancy week values.');const bmi=before/(height*height)*703;const group=bmi<18.5?'Underweight':bmi<25?'Normal weight':bmi<30?'Overweight':'Obesity';const single={Underweight:[28,40],'Normal weight':[25,35],Overweight:[15,25],Obesity:[11,20]};const twin={Underweight:[50,62],'Normal weight':[37,54],Overweight:[31,50],Obesity:[25,42]};const total=(babies==='twins'?twin:single)[group],gain=current-before;let pace='Not calculated for twins';if(babies==='singleton'){const weekly={Underweight:[.97,1.28],'Normal weight':[.77,1.1],Overweight:[.51,.73],Obesity:[.37,.6]}[group];const elapsed=Math.max(0,week-13);const low=Math.min(total[0],(Math.min(week,13)/13)*1.1+elapsed*weekly[0]);const high=Math.min(total[1],(Math.min(week,13)/13)*4.4+elapsed*weekly[1]);pace=fmt(low)+'–'+fmt(high)+' lb planning range by week '+week;}show('Pre-pregnancy BMI category',group+' ('+fmt(bmi)+')',[['Weight gained so far',fmt(gain)+' lb'],['CDC total gain guideline',total[0]+'–'+total[1]+' lb'],['Pregnancy type',babies==='twins'?'Twins':'One baby'],['Trimester',week<=13?'First':week<=27?'Second':'Third'],['Singleton planning trajectory',pace]],'This is a guideline comparison, not a target or assessment. Weight changes can reflect fluid, fetal growth, placenta, blood volume, illness, or measurement timing. Contact your prenatal clinician about sudden gain or loss, swelling, vomiting, or any concern.');}
  function bodyfat(){const sex=$('sex').value,height=num('height'),neck=num('neck'),waist=num('waist'),hip=num('hip'),weight=num('weight');if(height<=0||neck<=0||waist<=0||weight<=0)return fail('Enter positive height, weight, neck, and waist measurements.');let bf;if(sex==='male'){if(waist<=neck)return fail('Waist must be larger than neck for this equation.');bf=86.010*Math.log10(waist-neck)-70.041*Math.log10(height)+36.76;}else{if(hip<=0||waist+hip<=neck)return fail('Enter a positive hip measurement and valid circumferences.');bf=163.205*Math.log10(waist+hip-neck)-97.684*Math.log10(height)-78.387;}if(!Number.isFinite(bf)||bf<2||bf>70)return fail('These measurements produce a result outside the method’s plausible range. Recheck tape placement and units.');const fat=weight*bf/100,lean=weight-fat;show('Estimated body fat',fmt(bf)+'%',[['Estimated fat mass',fmt(fat)+' lb'],['Estimated lean body mass',fmt(lean)+' lb'],['Method','U.S. Navy circumference equation'],['Measurements used',sex==='male'?'height, neck, abdomen':'height, neck, waist, hip']], 'Circumference equations are screening estimates and can be off by several percentage points, especially with unusual muscularity, fat distribution, hydration, or inconsistent tape placement. They are not a medical diagnosis or an official service assessment.');}
  function tdee(){const age=num('age'),weightLb=num('weight'),heightIn=num('height'),activity=num('activity');if(age<50||age>100||weightLb<=0||heightIn<=0)return fail('Enter an age of 50 or older and positive height and weight.');const kg=weightLb*.45359237,cm=heightIn*2.54,bmr=10*kg+6.25*cm-5*age-161,tdee=bmr*activity;show('Estimated daily energy expenditure',Math.round(tdee).toLocaleString()+' kcal/day',[['Resting energy estimate',Math.round(bmr).toLocaleString()+' kcal/day'],['Activity multiplier',fmt(activity,3)],['Practical uncertainty range',Math.round(tdee*.9).toLocaleString()+'–'+Math.round(tdee*1.1).toLocaleString()+' kcal/day'],['Equation','Mifflin–St Jeor for women']], 'No universal, validated “menopause subtraction” is applied. The equation already includes age, but actual needs vary with lean mass, symptoms, medications, thyroid status, sleep, illness, and measured activity. Use weight trends and professional guidance rather than treating one estimate as a prescription.');}
  function heart(){const age=num('age'),rest=num('resting'),method=$('maxMethod').value;if(age<18||age>100||rest<35||rest>120)return fail('Enter an adult age and a plausible resting heart rate from 35 to 120 bpm.');const max=method==='tanaka'?208-.7*age:220-age;if(rest>=max)return fail('Resting heart rate must be below the estimated maximum. Ask a clinician for an individualized range.');const reserve=max-rest,zone=(a,b)=>Math.round(rest+reserve*a)+'–'+Math.round(rest+reserve*b)+' bpm';show('HIIT work-zone estimate',zone(.85,.95),[['Estimated maximum heart rate',Math.round(max)+' bpm'],['Heart-rate reserve',Math.round(reserve)+' bpm'],['Easy / recovery (50–60% HRR)',zone(.5,.6)],['Moderate (60–70% HRR)',zone(.6,.7)],['Vigorous (70–85% HRR)',zone(.7,.85)],['HIIT work interval (85–95% HRR)',zone(.85,.95)]], 'The Karvonen method personalizes zones with resting heart rate, but age-predicted maximum heart rate is still an average. Do not use this result to override symptoms, a clinician’s limit, cardiac rehabilitation guidance, or medication effects. Stop exercise and seek urgent care for chest pain, fainting, or severe breathing difficulty.');}
  const calculators={pregnancy,bodyfat,tdee,heart};
  function prefill(){const p=new URLSearchParams(location.search);document.querySelectorAll('[data-param]').forEach(el=>{if(p.has(el.dataset.param))el.value=p.get(el.dataset.param);});if([...p].length)$('calculate')?.click();}
  function share(){const u=new URL(location.origin+location.pathname);document.querySelectorAll('[data-param]').forEach(el=>{if(el.value!=='')u.searchParams.set(el.dataset.param,el.value);});navigator.clipboard.writeText(u.toString()).then(()=>{$('shareStatus').textContent='Shareable link copied.';setTimeout(()=>$('shareStatus').textContent='',3000);});}
  function reset(){document.querySelector('form')?.reset();$('results').innerHTML='<p class="ymyl-empty">Enter your measurements to see an estimate, its formula, and its limitations.</p>';history.replaceState({},'',location.pathname);}
  document.addEventListener('DOMContentLoaded',()=>{const fn=calculators[document.body.dataset.calculator];if(!fn)return;$('calculatorForm').addEventListener('submit',e=>{e.preventDefault();fn();});$('reset').addEventListener('click',reset);$('share').addEventListener('click',share);prefill();});
})();
